Vagrant.configure("2") do |config|
    config.vm.define :master do |master|
      master.vm.box = "ubuntu/jammy64"
      master.vm.define "master"
      master.vm.hostname = "salt"
      master.vm.network :private_network, ip: '192.168.56.2'
      master.vm.provision :shell, path: "scripts/master.sh", run: 'always'
    end
  
    config.vm.define :minion do |minion|
      minion.vm.box = "ubuntu/jammy64"
      minion.vm.define "minion"
      minion.vm.hostname = "salt"
      minion.vm.network :private_network, ip: '192.168.56.3'
      minion.vm.provision :shell, path: "scripts/minion.sh", run: 'always'
    end

end