Vagrant.configure("2") do |config|
    config.vm.define :master do |master|
      master.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
      end
      master.vm.box = "ubuntu/jammy64"
      master.vm.define "master"
      master.vm.hostname = "master"
      master.vm.network :private_network, ip: '192.168.56.2'
      master.vm.synced_folder "states/", "/srv/salt/states"
      master.vm.synced_folder "pillar", "/srv/salt/pillar"
      master.vm.provision :salt do |salt|
        salt.master_config = "config/master"
        salt.master_key = "ssh-keys/master-ssh.pem"
        salt.master_pub = "ssh-keys/master-ssh.pub"
        salt.minion_key = "ssh-keys/minion-ssh.pem"
        salt.minion_pub = "ssh-keys/minion-ssh.pub"
        salt.seed_master = {
          "minion" => "ssh-keys/minion-ssh.pub"
        }
        salt.install_type = "stable"
        salt.install_master = true
        salt.no_minion = true
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp -x python3"
      end
    end
  
    config.vm.define :minion do |minion|
      minion.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
      end
      minion.vm.box = "ubuntu/jammy64"
      minion.vm.define "minion"
      minion.vm.hostname = "minion"
      minion.vm.network :private_network, ip: '192.168.56.3'
      minion.vm.provision :salt do |salt|
        salt.minion_config = "config/minion"
        salt.minion_key = "ssh-keys/minion-ssh.pem"
        salt.minion_pub = "ssh-keys/minion-ssh.pub"
        salt.install_type = "stable"
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp -x python3"
      end
    end

end