php:
  version: '8.1'
  packages:
    fpm: 'fpm' 
    common: 'common' 
    mysql: 'mysql'
    xml: 'xml'
    xmlrpc: 'xmlrpc' 
    curl: 'curl' 
    gd: 'gd' 
    imagick: 'imagick' 
    cli: 'cli' 
    dev: 'dev' 
    imap: 'imap' 
    mbstring: 'mbstring'
    opcache: 'opache'
    soap: 'soap' 
    zip: 'zip' 
    redis: 'redis' 
    intl: 'intl'
    bcmath: 'bcmath'